const translations = {
  fr: {
              phOldPassword: "Entrez votre mot de passe actuel",
              phConfirmNewPassword: "Confirmer votre nouveau mot de passe",
              selectLanguage: "Sélectionnez une langue",
              frenchLang: "Français",
              englishLang: "Anglais",
            // Nouveaux ajouts pour parametre.html
            entryReminders: "Rappels de saisie",
            entryRemindersDesc: "Recevoir des rappels pour enregistrer vos transactions",
            oldPassword: "Ancien mot de passe",
            confirmNewPassword: "Confirmer le nouveau mot de passe",
            resetData: "Réinitialiser les données",
            sync: "Synchronisation",
            lastBackup: "Dernière sauvegarde",
            noBackup: "Aucune sauvegarde",
            exportData: "Exporter les données",
            importFile: "Importer un fichier",
            about: "À propos",
            version: "Version",
            versionValue: "--",
            credits: "Crédits",
            creditsValue: "Numera",
            privacy: "Confidentialité",
            readPolicy: "Lire la politique",
            sendFeedback: "Envoyer un retour",
            feedbackPlaceholder: "Partager vos suggestions...",
            send: "Envoyer",
            logout: "Déconnexion",
            logoutConfirm: "Êtes-vous sûr de vouloir quitter votre session ?",
            logoutYes: "Oui, me déconnecter",
            logoutCancel: "Annuler",
          budgetAdviceExceeded: "Budget dépassé",
          budgetAdviceAlmostReached: "Budget presque atteint",
          budgetAdviceWarning: "Attention à vos dépenses",
          budgetAdviceExcellent: "Gestion excellente",
          budgetAdviceError: "Impossible de charger les données budgétaires.",
          budgetAdviceNoBudget: "Aucun budget défini",
        activeAccount: "Compte Actif",
      // Placeholders
      phBudgetExample: "Ex: Courses alimentaires",
      phAmountZero: "0.00",
      selectCategory: "Sélectionnez une catégorie",
      category: "Catégorie",
      period: "Période",
      status: "Statut",
      errorTitle: "Erreur",
      okBtn: "OK",
    // Placeholders
    phBudgetExample: "Ex: Courses alimentaires",
    phAmountZero: "0.00",
    phEmail: "Entrez votre adresse email",
    phPassword: "Mot de passe",
    phUsername: "Nom d'utilisateur",
    phEmailLabel: "Adresse email",
    phConfirmPassword: "Confirmer mot de passe",
    phNewPassword: "Nouveau mot de passe",
    phFeedback: "Partager vos suggestions...",
    phNotSpecified: "Non spécifié",
    phEnterAmount: "Veuillez insérer un montant...",
    phTransactionDescription: "Description de la transaction...",
    phNoteDetail: "Notez un détail...",

    // Navigation ASIDE
    navDashboard: "Tableau de bord",
    navTransaction: "Transaction",
    navBudget: "Budget",
    navProfil: "Profil",
    navParametres: "Parametres",
    navDeconnexion: "Deconnexion",

    // Général
    send: "Envoyer",
    french: "Français",
    dashboard: "Tableau de bord",
    transaction: "Transaction",
    budget: "Budget",
    profile: "Profil",
    settings: "Paramètres",
    logout: "Déconnexion",
    user: "Utilisateur",

    // Dashboard
    totalBalance: "Solde total",
    monthlyIncome: "Revenu du mois",
    monthlyExpense: "Dépense du mois",
    quickSummary: "Voici votre résumé financier du mois",
    summaryDescription: "Suivez votre progression financière et maîtrisez votre budget pour atteindre vos objectifs",
    noRecentTransaction: "Aucune transaction récente effectuée",
    loadingError: "Erreur de chargement",
    totalExpenses: "Total dépenses :",
    noExpense: "Aucune dépense",
    addExpenseToSeeDistribution: "Ajoutez des dépenses pour voir la répartition.",
    monthsShort: ["Jan", "Fév", "Mar", "Avr", "Mai", "Jun", "Jul", "Aoû", "Sep", "Oct", "Nov", "Déc"],
    financialAnalysis: "Analyse des flux",
    expenseDistribution: "Répartition des dépenses",
    incomeVsExpense: "Dépense vs Revenu",
    flowAnalysis: "Analyse des Flux",
    sevenDays: "7J",
    oneMonth: "1M",
    threeMonths: "3M",
    oneYear: "1A",

    allocationofexpenses: "Repartition des Dépense",
    month: "Mois",
    year: "Année",
    recentTransactions: "Transactions récentes",
    allTypes: "Tous les types",
    income: "Revenu",
    expense: "Dépense",
    allCategories: "Toutes les catégories",

    // Table
    date: "Date",
    description: "Description",
    category: "Catégorie",
    type: "Type",
    amount: "Montant",
    seeMore: "Voir plus",

    // Déconnexion
    cancel: "Annuler",
    confirmLogout: "Oui, me déconnecter",
    logoutConfirmationMessage:
      "Êtes-vous sûr de vouloir quitter votre session ?",

    // Transactions
    addTransaction: "Ajouter une transaction",
    addTransactionForm: "Ajouter une transaction",
    select: "Sélectionner",
    selectOption: "Sélectionner",
    add: "Ajouter",
    optionalDescription: "Description (optionnelle)",
    descriptionOptional: "Description de la transaction...",
    all: "Tous",
    deleteAll: "Tout supprimer",
    deleteAllBtn: "Tout supprimer",
    revenues: "Revenus",
    expenses: "Dépenses",

    editTransaction: "Modifier la transaction",
    updateTransactionDetails: "Mettez à jour les détails de votre opération",
    saveChanges: "Enregistrer les modifications",

    deleteTransaction: "Supprimer la transaction",
    irreversibleAction: "Cette action est irréversible",

    // Landing / Présentation
    marketingText:
      "Optimisez vos finances avec des outils professionnels de suivi budgétaire",

    // Budgets
    budgetSummary: "Résumé des budgets",
    totalBudgeted: "Total Budgétisé",
    totalSpent: "Total Dépensé",
    balance: "Équilibre",
    activeBudgets: "Budgets Actifs",
    exceededBudgets: "Budgets Dépassés",
    totalBudgets: "Total Budgets",

    createNewBudget: "Créer un Nouveau Budget",
    budgetName: "Nom du Budget",
    budgetNameHint: "Choisir un nom descriptif pour votre budget",
    budgetNameHelp: "Choisissez un nom descriptif pour votre budget.",    budgetDescription: "Définissez vos limites pour une meilleure santé financière.",    maxAmountHint: "Entrer le montant maximum alloué",
    selectCategory: "Sélectionnez une catégorie",

    food: "Alimentation",
    salary: "Salaire",
    bonus: "Prime",
    clothing: "Vêtements",
    communication: "Communication",
    finance: "Finance",
    insurance: "Assurances",
    taxes: "Impôts",
    subscriptions: "Abonnements",
    gifts: "Cadeaux",
    other: "Divers",
    side_activity: "Activité secondaire",
    business: "Business",
    stock_market: "Bourse",
    family_support: "Aide familiale",
    investments: "Investissements",
    sales: "Ventes",
    refunds: "Remboursements",
    exceptional_gains: "Gains exceptionnels",
    other_income: "Autres revenus",
    transport: "Transport",
    leisure: "Loisirs",
    health: "Santé",
    housing: "Logement",
    education: "Éducation",
    other: "Autre",

    categorizeBudget: "Catégorisez votre budget pour un meilleur suivi",

    period: "Période",
    monthly: "Mensuel",
    weekly: "Hebdomadaire",
    yearly: "Annuel",
    active: "Actif",
    exceeded: "Dépassé",
    renewalFrequency: "Définir la fréquence de renouvellement",
    createBudget: "Créer le budget",
    reset: "Réinitialiser",

    yourActiveBudgets: "Vos budgets actifs",
    filter: "Filtrer",
    noBudgetMessage:
      "Aucun budget créé pour le moment. Commencez par en ajouter un !",
    noBudgetFilters: "Aucun budget trouvé pour ces filtres.",

    // Paramètres
    mainCurrency: "Devise principale",
    budgetAlert: "Notification de dépassement",
    budgetAlertDesc: "Alerte en cas de dépassement de budget",

    security: "Sécurité",
    changePassword: "Modifier le mot de passe",
    savePassword: "Enregistrer le mot de passe",
    resetLocalData: "Réinitialiser les données locales",

    synchronization: "Synchronisation",
    lastBackup: "Dernière sauvegarde",
    noBackup: "Aucune sauvegarde",
    importFile: "Importer un fichier",

    about: "À propos",
    version: "Version",
    credits: "Crédits",
    privacy: "Confidentialité",
    readPolicy: "Lire la politique",
    sendFeedback: "Envoyer un retour",

    // Modifier budget
    editBudget: "Modifier le budget",
    save: "Enregistrer",
    confirmation: "Confirmation",
    deleteBudgetConfirm: "Êtes-vous sûr de vouloir supprimer ce budget ?",

    // Options & Select
    selectLanguage: "Selectionnez une langue",
    french: "Français",
    english: "Anglais",
    selectBudgetCategory: "Sélectionnez une catégorie",
    
    // Toast Messages
    transactionAdded: "Transaction ajoutée !",
    transactionEdited: "Transaction modifiée !",
    transactionDeleted: "Transaction supprimée !",
    allTransactionsDeleted: "Toutes les transactions supprimées !",
    historyCleared: "Historique vidé !",
    transactionModified: "Transaction modifié !",
    noTransactionsFound: "Aucune transaction trouvée",
    budgetCreatedSuccess: "Budget créé avec succès!",
    budgetUpdatedSuccess: "Budget modifié avec succès!",
    budgetDeleted: "Budget supprimé",
    allBudgetsDeleted: "Tous les budgets supprimés!",
    photoUpdated: "Photo de profil mise à jour avec succès !",
    profileUpdated: "Profil mis à jour avec succès !",
    profileUpdateError: "Erreur lors de la mise à jour du profil.",
    networkError: "Erreur réseau. Veuillez réessayer plus tard.",
    dataExported: "Données exportées avec succès !",
    languageChanged: "Langue changée avec succès !",
    profileExportError: "Impossible d'exporter : utilisateur non authentifié",
    editProfilePhoto: "Modifier la photo de profil",
    chooseFile: "Choisir une image",
    upload: "Uploader",
    // Messages paramétrages
    dataReset: "Données réinitialisées !",
    currencyUpdated: "Devise principale mise à jour !",
    darkModeEnabled: "Mode sombre activé ✨",
    darkModeDisabled: "Mode clair activé ☀️",
    remindersEnabled: "Rappels activés !",
    remindersDisabled: "Rappels désactivés",
    budgetOverrunEnabled: "Notifications de dépassement activées !",
    budgetOverrunDisabled: "Notifications de dépassement désactivées",
    languageUpdateError: "Erreur lors de la mise à jour de la langue",
    // Preview et devises
    bgPreview: "Fond",
    accentPreview: "Accent",
    borderPreview: "Bordure",
    fcfaCurrency: "FCFA (XAF)",
    euroCurrency: "Euro (€)",
    dollarCurrency: "Dollar US ($)",
    // Erreurs formulaires mot de passe
    errorPasswordFieldsRequired: "Tous les champs de mot de passe sont obligatoires.",
    errorPasswordMinLength: "Le nouveau mot de passe doit contenir au moins 8 caractères.",
    errorPasswordMismatch: "Les nouveaux mots de passe ne correspondent pas.",
    errorPasswordSame: "Le nouveau mot de passe doit être différent de l'ancien.",
    passwordChangeSuccess: "Mot de passe mis à jour avec succès !",
    passwordChangeError: "Erreur lors du changement de mot de passe.",
    networkError2: "Erreur réseau. Veuillez réessayer.",
    exportError: "Impossible d'exporter les données. Veuillez réessayer.",
    exportErrorNetwork: "Erreur réseau. Veuillez vérifier votre connexion.",
    resetConfirmTitle: "Réinitialisation",
    resetConfirmMessage: "Êtes-vous sûr ? Toutes vos transactions et vos budgets seront définitivement supprimés.",
    resetSuccess: "Données réinitialisées avec succès.",
    resetError: "Erreur lors de la réinitialisation.",
    // Button Labels
    buttonUnderstood: "Compris",
    buttonCancel: "Annuler",
    buttonConfirmDelete: "Supprimer",
    buttonConfirmReset: "Réinitialiser",
    // Popup Titles
    popupErrorTitle: "Erreur",
    popupSuccessTitle: "Succès",
    
    // Error Messages
    futuresDatesNotAllowed: "Les dates futures sont interdites",
    dateTooOld: "Vous ne pouvez pas sélectionner une date antérieure à 1 mois",
    budgetExceeded: "Budget exceeded!",
    budgetExceededAlert: "Alert: Budget exceeded!",
    
    // Placeholders
    phBudgetName: "Ex: Courses alimentaires",
    phBudgetAmount: "0.00",
    phTransactionAmount: "Veuillez saisir un montant...",
    phTransactionDescription: "Description de la transaction...",
    phNoteDetail: "Ajoutez un détail...",
    phFeedback: "Partager vos suggestions...",
    phSelectLanguage: "Sélectionnez une langue",
    phNotSpecified: "Non spécifié",
    editTransactionTitle: "Modifier la transaction",
    updateDetailsMessage: "Mettez à jour les détails de votre opération",
    confirmDelete: "Supprimer",
    cancelDelete: "Annuler",
    irreversibleAction: "Cette action est irréversible.",
    fillAllFields: "Veuillez remplir tous les champs correctement.",
    viewMore: "Voir plus",
    viewLess: "Voir moins",
    
    budgetDeleted: "Budget supprimé",
    deleteAllBudgets: "Supprimer tous les budgets ?",
    confirmDeleteBudget: "Êtes-vous sûr de vouloir supprimer ce budget ?",
    editBudget: "Modifier le Budget",
    editButtonLabel: "Modifier",
    deleteButtonLabel: "Supprimer",
    createBudgetBtn: "Créer le Budget",
    errorBudgetName: "Veuillez entrer un nom de budget.",
    errorSelectCategory: "Veuillez sélectionner une catégorie.",
    errorBudgetAmount: "Veuillez entrer un montant valide.",
    errorSelectPeriod: "Veuillez choisir une période.",
    budgetAlreadyExists: "Un budget existe déjà pour cette catégorie et cette période.",
    errorCreatingBudget: "Erreur lors de la création.",
    errorModifyingBudget: "Erreur lors de la modification.",
    errorDeletingBudget: "Erreur lors de la suppression.",
    resetBtn: "Réinitialiser",
    budgetCreated: "Budget créé avec succès!",
    budgetUpdated: "Budget mis à jour!",
    
    yourActiveBudgets: "Vos Budgets Actifs",
    filterBudgets: "Filtrer",
    clearAllBudgets: "Tout supprimer",
    quickNavigation: "Navigation rapide",
    accessDashboard: "Accéder au Tableau de bord",
    manageBudgets: "Gérer vos budgets",

    personalInfo: "Informations Personnelles",
    personalInfoDesc: "Gérez vos coordonnées personnelles",
    fullName: "Nom complet",
    phone: "Téléphone",
    email: "Email",
    editProfile: "Modifier le profil",
    deleteProfilePhoto: "Supprimer photo",
    deleteProfilePhotoSuccess: "Photo de profil supprimée avec succès",
    deleteProfilePhotoError: "Erreur lors de la suppression de la photo",
    noPhotoToDelete: "Aucune photo à supprimer",
    notSpecified: "Non spécifié",

    budgetOverview: "Aperçu Budgétaire",
    budgetOverviewDesc: "Vue d'ensemble de vos budgets et dépenses",
    used: "Utilisé",
    remaining: "Restant",
    spending: "Dépensé",
    budgetTip: "Votre budget est sous contrôle.",

    accountInfo: "Informations de compte",
    technicalDetails: "Détails techniques et registres d'accès",
    userId: "Identifiant Utilisateur",
    creationDate: "Date de création",
    lastLogin: "Dernière connexion",

    securityData: "Sécurité et Données",
    securityDataDesc: "Gérez vos données de compte et votre sécurité",
    manageAccountData: "Gérez vos données de compte, exportez vos transactions ou supprimez votre profil.",
    twoFactorAuth: "Two-Factor Auth",
    twoFactorAuthDesc: "Activé via Authentificateur",
    activeSessions: "Active Sessions",
    activeSessionsDesc: "0 appareils connectés",
    exportData: "Exporter les données",
    deleteAccount: "Supprimer le compte",
    editInfoTitle: "Modifier les informations",
    cancel: "Annuler",
    saveChanges: "Enregistrer les modifications",
    deleteAccountTitle: "Suppression du compte",
    deleteAccountConfirm: "Êtes-vous sûr de vouloir supprimer votre compte ? Cette action est irréversible.",
    confirmDelete: "Oui, supprimer",
    logoutTitle: "Déconnexion",
    logoutConfirm: "Êtes-vous sûr de vouloir quitter votre session ?",
    confirmLogout: "Oui, me déconnecter",

    // Apparence
    appearance: "Apparence",
    darkMode: "Mode sombre",
    reduceEyeStrain: "Réduire la fatigue oculaire",
    accentColor: "Couleur d’accent",
    customizeUI: "Personnaliser l’interface",
    themePreview: "Aperçu du thème",

    generalPreferences: "Préférences générales",
    language: "Langue",
    frenchLang: "Français",
    englishLang: "Anglais",
    
    // Budget page
    budgetsStats: "Statistiques des Budgets",
    architectMessage: "Organisez vos finances avec la précision d'un architecte.",
    confirmDeleteAllBudgets: "Voulez-vous vraiment supprimer tous les budgets ?",
    deleteAll: "Supprimer tout",

    // Notifications
    notif_income_title: "Revenu reçu",
    notif_expense_title: "Dépense enregistrée",
    notif_budget_exceeded_title: "Budget dépassé!",
    notif_budget_warning_title: "Budget presque atteint",
    notif_budget_info_title: "Gestion budgétaire",
    noNotifications: "Aucune notification",
    
    // Time ago translations
    justNow: "À l'instant",
    minutesAgo: "Il y a {count}m",
    hoursAgo: "Il y a {count}h",
    daysAgo: "Il y a {count}j",
    
    // Avatar upload translations
    selectImage: "Veuillez sélectionner une image",
    unsupportedFile: "Fichier non pris en charge. Veuillez uploader une image (JPG ou PNG)",
    fileTooLarge: "Le fichier est trop volumineux (max 2MB)",
    
    // Reminder toast
    reminderTitle: "Rappel de saisie",
    reminderText: "N'oubliez pas d'enregistrer vos dernières transactions pour un suivi précis.",
    reminderButton: "D'accord",
    
    // Transaction notifications
    notificationNoTransactionWeek: "Aucune transaction enregistrée depuis plus de 7 jours. Pensez à suivre vos dépenses.",
    notificationNoTransactionToday: "Aucune transaction enregistrée aujourd'hui. N'oubliez pas d'ajouter vos dépenses.",
    notificationTransactionButton: "Saisir",
    
    // Notification badge
    noNotifications: "Aucune notification",
    newNotifications: "{count} nouveau{plural}",
    notificationsLabel: "Notifications",
    markAllAsRead: "Tout marquer comme lu",
    deleteAllNotifications: "Tout supprimer",
  },



// --- ANGLAIS ---



  en: {
                phOldPassword: "Enter your current password",
                phConfirmNewPassword: "Confirm your new password",
                selectLanguage: "Select a language",
                frenchLang: "French",
                englishLang: "English",
              // New additions for parametre.html
              entryReminders: "Entry reminders",
              entryRemindersDesc: "Receive reminders to record your transactions",
              oldPassword: "Old password",
              confirmNewPassword: "Confirm new password",
              resetData: "Reset data",
              sync: "Synchronization",
              lastBackup: "Last backup",
              noBackup: "No backup",
              exportData: "Export data",
              importFile: "Import file",
              about: "About",
              version: "Version",
              versionValue: "--",
              credits: "Credits",
              creditsValue: "Numera",
              privacy: "Privacy",
              readPolicy: "Read policy",
              sendFeedback: "Send feedback",
              feedbackPlaceholder: "Share your suggestions...",
              send: "Send",
              logout: "Logout",
              logoutConfirm: "Are you sure you want to end your session?",
              logoutYes: "Yes, log me out",
              logoutCancel: "Cancel",
            budgetAdviceExceeded: "Budget exceeded",
            budgetAdviceAlmostReached: "Budget almost reached",
            budgetAdviceWarning: "Watch your spending",
            budgetAdviceExcellent: "Excellent management",
            budgetAdviceError: "Unable to load budget data.",
            budgetAdviceNoBudget: "No budget defined",
          activeAccount: "Active Account",
        securityData: "Security and Data",
        securityDataDesc: "Manage your account data and security",
        manageAccountData: "Manage your account data, export your transactions or delete your profile.",
        twoFactorAuth: "Two-Factor Auth",
        twoFactorAuthDesc: "Currently Enabled via Authenticator",
        activeSessions: "Active Sessions",
        activeSessionsDesc: "0 devices connected",
        exportData: "Export data",
        deleteAccount: "Delete account",
        editInfoTitle: "Edit information",
        cancel: "Cancel",
        saveChanges: "Save changes",
        deleteAccountTitle: "Delete account",
        deleteAccountConfirm: "Are you sure you want to delete your account? This action is irreversible.",
        confirmDelete: "Yes, delete",
        logoutTitle: "Logout",
        logoutConfirm: "Are you sure you want to end your session?",
        confirmLogout: "Yes, log me out",
      errorTitle: "Error",
      okBtn: "OK",
    transactionAdded: "Transaction added!",
    futuresDatesNotAllowed: "Future dates are not allowed",
    dateTooOld: "You cannot select a date older than 1 month",
    // Placeholders
    phBudgetExample: "Ex: Grocery shopping",
    phAmountZero: "0.00",
    selectCategory: "Select a category",
    category: "Category",
    period: "Period",
    status: "Status",
    phEmail: "Enter your email address",
    phPassword: "Password",
    phUsername: "Username",
    phEmailLabel: "Email address",
    phConfirmPassword: "Confirm password",
    phNewPassword: "New password",
    phFeedback: "Share your suggestions...",
    phNotSpecified: "Not specified",
    phEnterAmount: "Please enter an amount...",
    phTransactionAmount: "Please enter an amount...",
    phTransactionDescription: "Transaction description...",
    phNoteDetail: "Note a detail...",

    // Navigation ASIDE
    navDashboard: "Dashboard",
    navTransaction: "Transaction",
    navBudget: "Budget",
    navProfil: "Profile",
    navParametres: "Settings",
    navDeconnexion: "Logout",

    // General
    send: "Send",
    french: "French",
    dashboard: "Dashboard",
    transaction: "Transaction",
    budget: "Budget",
    profile: "Profile",
    settings: "Settings",
    logout: "Logout",
    user: "User",

    // Dashboard
    totalBalance: "Total balance",
    monthlyIncome: "Monthly income",
    monthlyExpense: "Monthly expense",
    quickSummary: "Here is your monthly financial summary",
    summaryDescription: "Monitor your financial progress and take control of your budget to achieve your goals",
    noRecentTransaction: "No recent transaction performed",
    totalExpenses: "Total expenses:",
    noExpense: "No expense",
    addExpenseToSeeDistribution: "Add expenses to see the distribution.",
    monthsShort: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
    financialAnalysis: "Financial flow analysis",
    expenseDistribution: "Expense distribution",
    incomeVsExpense: "Expense vs Income",
    flowAnalysis: "Flow Analysis",
    sevenDays: "7D",
    oneMonth: "1M",
    threeMonths: "3M",
    oneYear: "1Y",

    budgetByCategory: "Budget by category",
    month: "Month",
    year: "Year",
    recentTransactions: "Recent transactions",
    allTypes: "All types",
    income: "Income",
    expense: "Expense",
    allCategories: "All categories",

    // Table
    date: "Date",
    description: "Description",
    category: "Category",
    type: "Type",
    amount: "Amount",
    seeMore: "See more",

    // Logout
    cancel: "Cancel",
    confirmLogout: "Yes, log me out",
    logoutConfirmationMessage: "Are you sure you want to end your session?",

    // Transactions
    addTransaction: "Add transaction",
    addTransactionForm: "Add a transaction",
    select: "Select",
    selectOption: "Select",
    add: "Add",
    optionalDescription: "Description (optional)",
    descriptionOptional: "Transaction description...",
    all: "All",
    deleteAll: "Delete all",
    deleteAllBtn: "Delete all",
    revenues: "Income",
    expenses: "Expenses",

    editTransaction: "Edit transaction",
    updateTransactionDetails: "Update the details of your operation",
    saveChanges: "Save changes",

    deleteTransaction: "Delete transaction",
    irreversibleAction: "This action is irreversible",

    // Landing
    marketingText: "Optimize your finances with professional budgeting tools",

    // Budgets
    budgetSummary: "Budget summary",
    totalBudgeted: "Total Budgeted",
    totalSpent: "Total Spent",
    balance: "Balance",
    activeBudgets: "Active Budgets",
    exceededBudgets: "Exceeded Budgets",
    totalBudgets: "Total Budgets",

    createNewBudget: "Create a New Budget",
    budgetName: "Budget Name",
    budgetNameHint: "Choose a descriptive name for your budget",
    budgetNameHelp: "Choose a descriptive name for your budget.",
    budgetDescription: "Set your limits for better financial health.",
    maxAmountHint: "Enter the maximum allocated amount",
    selectCategory: "Select a category",

    food: "Food",
    salary: "Salary",
    bonus: "Bonus",
    clothing: "Clothing",
    communication: "Communication",
    finance: "Finance",
    insurance: "Insurance",
    taxes: "Taxes",
    subscriptions: "Subscriptions",
    gifts: "Gifts",
    other: "Other",
    side_activity: "Side activity",
    business: "Business",
    stock_market: "Stock market",
    family_support: "Family support",
    investments: "Investments",
    sales: "Sales",
    refunds: "Refunds",
    exceptional_gains: "Exceptional gains",
    other_income: "Other income",
    transport: "Transport",
    leisure: "Leisure",
    health: "Health",
    housing: "Housing",
    education: "Education",
    other: "Other",

    categorizeBudget: "Categorize your budget for better tracking",

    period: "Period",
    monthly: "Monthly",
    weekly: "Weekly",
    yearly: "Yearly",
    active: "Active",
    exceeded: "Exceeded",
    renewalFrequency: "Set renewal frequency",
    createBudget: "Create budget",
        profileExportError: "Export failed: user not authenticated",
    dataExported: "Data exported successfully!",
    photoUpdated: "Profile photo updated successfully!",
    profileUpdated: "Profile updated successfully!",
    profileUpdateError: "Error updating profile.",
    networkError: "Network error. Please try again later.",
    editProfilePhoto: "Edit profile photo",
    chooseFile: "Choose an image",
    upload: "Upload",
    reset: "Reset",

    yourActiveBudgets: "Your active budgets",
    filter: "Filter",
    noBudgetMessage: "No budget created yet. Start by adding one!",
    noBudgetFilters: "No budget found for these filters.",

    // Settings
    mainCurrency: "Main currency",
    budgetAlert: "Overspending notification",
    budgetAlertDesc: "Alert when budget is exceeded",

    security: "Security",
    changePassword: "Change password",
    savePassword: "Save password",
    resetLocalData: "Reset local data",

    synchronization: "Synchronisation",
    lastBackup: "Last backup",
    noBackup: "No backup",
    importFile: "Import file",

    about: "About",
    version: "Version",
    credits: "Credits",
    privacy: "Privacy",
    readPolicy: "Read policy",
    sendFeedback: "Send feedback",

    // Edit budget
    editBudget: "Edit budget",
    save: "Save",
    confirmation: "Confirmation",
    deleteBudgetConfirm: "Are you sure you want to delete this budget?",

    // Modals & Popups
    deleteTransactionTitle: "Delete transaction ?",
    editTransactionTitle: "Edit transaction",
    updateDetailsMessage: "Update the details of your operation",
    confirmDelete: "Delete",
    cancelDelete: "Cancel",
    irreversibleAction: "This action is irreversible.",
    fillAllFields: "Please fill all fields correctly.",
    viewMore: "View more",
    viewLess: "View less",
    historyCleared: "History cleared!",
    transactionModified: "Transaction modified!",
    noTransactionsFound: "No transactions found",
    
    budgetCreatedSuccess: "Budget created successfully!",
    budgetUpdatedSuccess: "Budget updated successfully!",
    budgetDeleted: "Budget deleted",
    allBudgetsDeleted: "All budgets deleted!",
    photoUpdated: "Profile photo updated successfully!",
    profileUpdated: "Profile updated successfully!",
    profileUpdateError: "Error updating profile.",
    networkError: "Network error. Please try again later.",
    dataExported: "Data exported successfully!",
    languageChanged: "Language changed successfully!",
    profileExportError: "Unable to export: user not authenticated",
    // Settings messages
    dataReset: "Data reset!",
    currencyUpdated: "Main currency updated!",
    darkModeEnabled: "Dark mode enabled ✨",
    darkModeDisabled: "Light mode enabled ☀️",
    remindersEnabled: "Reminders enabled!",
    remindersDisabled: "Reminders disabled",
    budgetOverrunEnabled: "Budget overrun notifications enabled!",
    budgetOverrunDisabled: "Budget overrun notifications disabled",
    languageUpdateError: "Error updating language",
    // Preview et devises
    bgPreview: "Background",
    accentPreview: "Accent",
    borderPreview: "Border",
    fcfaCurrency: "FCFA (XAF)",
    euroCurrency: "Euro (€)",
    dollarCurrency: "US Dollar ($)",
    // Password form errors
    errorPasswordFieldsRequired: "All password fields are required.",
    errorPasswordMinLength: "New password must contain at least 8 characters.",
    errorPasswordMismatch: "New passwords do not match.",
    errorPasswordSame: "New password must be different from the old one.",
    passwordChangeSuccess: "Password updated successfully!",
    passwordChangeError: "Error changing password.",
    networkError2: "Network error. Please try again.",
    exportError: "Unable to export data. Please try again.",
    exportErrorNetwork: "Network error. Please check your connection.",
    resetConfirmTitle: "Reset Data",
    resetConfirmMessage: "Are you sure? All your transactions and budgets will be permanently deleted.",
    resetSuccess: "Data reset successfully.",
    resetError: "Error resetting data.",
    // Button Labels
    buttonUnderstood: "Got It",
    buttonCancel: "Cancel",
    buttonConfirmDelete: "Delete",
    buttonConfirmReset: "Reset",
    // Popup Titles
    popupErrorTitle: "Error",
    popupSuccessTitle: "Success",
    
    deleteAllBudgets: "Delete all budgets?",
    confirmDeleteBudget: "Are you sure you want to delete this budget?",
    editBudget: "Edit Budget",
    editButtonLabel: "Edit",
    deleteButtonLabel: "Delete",
    createBudgetBtn: "Create Budget",
    errorBudgetName: "Please enter a budget name.",
    errorSelectCategory: "Please select a category.",
    errorBudgetAmount: "Please enter a valid amount.",
    errorSelectPeriod: "Please choose a period.",
    budgetAlreadyExists: "A budget already exists for this category and period.",
    errorCreatingBudget: "Error creating budget.",
    errorModifyingBudget: "Error modifying budget.",
    errorDeletingBudget: "Error deleting budget.",
    resetBtn: "Reset",
    
    yourActiveBudgets: "Your Active Budgets",
    filterBudgets: "Filter",
    clearAllBudgets: "Delete all",
    quickNavigation: "Quick navigation",
    accessDashboard: "Access Dashboard",
    manageBudgets: "Manage your budgets",

    personalInfo: "Personal Information",
    personalInfoDesc: "Manage your personal information",
    fullName: "Full name",
    phone: "Phone",
    email: "Email",
    editProfile: "Edit profile",
    deleteProfilePhoto: "Delete photo",
    deleteProfilePhotoSuccess: "Profile photo deleted successfully",
    deleteProfilePhotoError: "Error deleting profile photo",
    noPhotoToDelete: "No photo to delete",
    notSpecified: "Not specified",

    budgetOverview: "Budget Overview",
    budgetOverviewDesc: "Overview of your budgets and spending",
    used: "Used",
    remaining: "Remaining",
    spending: "Spending",
    budgetTip: "Your budget is under control.",

    accountInfo: "Account Information",
    technicalDetails: "Technical details and access logs",
    userId: "User ID",
    creationDate: "Creation date",
    lastLogin: "Last login",

    securityAndData: "Security and Data",
    securityDataDesc: "Manage your account data and security",
    manageAccountData: "Manage your account data, export your transactions",
    deleteProfile: "Or delete your profile",
    exportData: "Export data",
    deleteAccount: "Delete account",
    editInfo: "Edit information",

    // Appearance
    appearance: "Appearance",
    darkMode: "Dark mode",
    reduceEyeStrain: "Reduce eye strain",
    accentColor: "Accent color",
    customizeUI: "Customize interface",
    themePreview: "Theme preview",

    generalPreferences: "General preferences",
    language: "Language",
    frenchLang: "French",
    englishLang: "English",
    
    // Budget page
    budgetsStats: "Budget Statistics",
    architectMessage: "Organize your finances with the precision of an architect.",
    confirmDeleteAllBudgets: "Are you sure you want to delete all budgets?",
    deleteAll: "Delete all",

    // Notifications
    notif_income_title: "Income received",
    notif_expense_title: "Expense recorded",
    notif_budget_exceeded_title: "Budget exceeded!",
    notif_budget_warning_title: "Budget almost reached",
    notif_budget_info_title: "Budget management",
    noNotifications: "No notifications",
    
    // Time ago translations
    justNow: "Just now",
    minutesAgo: "{count}m ago",
    hoursAgo: "{count}h ago",
    daysAgo: "{count}d ago",
    
    // Avatar upload translations
    selectImage: "Please select an image",
    unsupportedFile: "Unsupported file. Please upload an image (JPG or PNG)",
    fileTooLarge: "File is too large (max 2MB)",
    
    // Reminder toast
    reminderTitle: "Entry reminder",
    reminderText: "Don't forget to record your latest transactions for accurate tracking.",
    reminderButton: "Okay",
    
    // Transaction notifications
    notificationNoTransactionWeek: "No transactions recorded for more than 7 days. Remember to track your spending.",
    notificationNoTransactionToday: "No transactions recorded today. Don't forget to add your expenses.",
    notificationTransactionButton: "Add",
    
    // Notification badge
    noNotifications: "No notifications",
    newNotifications: "{count} new",
    notificationsLabel: "Notifications",
    markAllAsRead: "Mark all as read",
    deleteAllNotifications: "Delete all",

  },
};
